### ISSUE TITLE
[BUG] 모델 안 되는 경우

### ISSUE THREAD

**Issue by han16935** [GCU-Home-Protector/YouTube#2]
Flask 적용해서 결과 15주차 레포트 제일 윗 부분에 올려놧는데 안 되는 경우가
- 계속 한 감정만 추천받다가 다른 감정에 대해 추천해달라 하면 "좋아요 누른 노래들이 데이터베이스에 없습니다." 가 발생해요
- Neutral 경우에는 처음에만 제대로 추천되다가 두 번째부터 위 메시지가 발생해요

**Comment by YongwanJoo** [comment]
계속 한 감정만 추천받다가 다른 감정에 대해 추천해달라 하면 "좋아요 누른 노래들이 데이터베이스에 없습니다." 가 발생해요
ㄴ> 해당 이슈는 유사도 매트릭스를 감정별로 구현해서 그렇습니다  liked_songs를  state 별로 {state} + like_songs 의 형식으로 따로 지정하고 현재 상태에 해당하는 좋아요 누른 노래들이 없으면 해당 state에서 첫 추천 리스트를 불러오는 방향으로 구현이 나을거 같습니다
Neutral 경우에는 처음에만 제대로 추천되다가 두 번째부터 위 메시지가 발생해요
ㄴ> 제가 지금 현우님 flask가 안돌아가는데 스크린샷으로 먼저 문제를 확인할 수 있을까요?

**Comment by han16935** [comment]
두 번째는 postman에서![image.png](https://prod-files-secure.s3.us-west-2.amazonaws.com/200194a5-0e6f-45d6-b0cd-dd5083577e08/6d19bc44-0bb4-4dd4-b58f-3fc4ccec171c/image.png) 
body에 추천받고 싶은 state 값 넣어서 send 누르시면 되고, 첫 번째는 제가 잘 모르겟어서 그런데 코드 수정해서 push해 주실 수 있나요? recommend_service의 recommend()에 추천 로직 넣엇습니다

**Comment by han16935** [comment]
![스크린샷 2024-12-16 190759](https://github.com/user-attachments/assets/c1a4e94c-3d9c-4f50-ab56-b3649bd01d47)

**Comment by YongwanJoo** [comment]
state 별 배열은 가지는 set를 만들었습니다.
